import { createConstants } from '../utils/constants.js';

const actionTypes = createConstants(
  'CHANGE_CONFIG',
  'RIGHT_CLICK_CELL',
  'RIGHT_CLICK_ON_BOMB',
  'LEFT_CLICK_CELL',
  'NEW_GRID',
  'NEW_STOPWATCH',
  'UPDATE_STOPWATCH',
  'SET_GRID',
  'SET_MINES_QUANTITY'
);

const cellStatus = createConstants(
  'CELL_INITIAL',
  'CELL_PRESSED',
  'CELL_BOMB',
  'CELL_FLAG',
  'CELL_BOMB_FLAG'
);

const COL_BEGINNER = 8;
const ROW_BEGINNER = 8;
const MINES_BEGINNER = 10;

const COL_INTERMEDIATE = 16;
const ROW_INTERMEDIATE = 16;
const MINES_INTERMEDIATE = 40;

const COL_EXPERT = 16;
const ROW_EXPERT = 16;
const MINES_EXPERT = 50;


const STOPWATCH_INITIAL_VALUE = '00:00:00';

export {
  actionTypes,
  cellStatus,
  STOPWATCH_INITIAL_VALUE,
  COL_BEGINNER,
  ROW_BEGINNER,
  MINES_BEGINNER,
  COL_INTERMEDIATE,
  ROW_INTERMEDIATE,
  MINES_INTERMEDIATE,
  COL_EXPERT,
  ROW_EXPERT,
  MINES_EXPERT
}
